Feat/merchant rules
backpack-fux/pylon-v2 pull request #9
Opened 2024-06-09 14:29 UTC by Dyl4n-C0de

- updated merchant duplication in the middleware
- updated the create merchant schema for input validation
- types/transaction.ts was added for the country, and state codes

2024-06-09 20:12 UTC, thomas779 requested changes

2024-06-09 20:12 UTC, thomas779 commented on src/v1/middleware.ts
> +  const merchant = await prisma.merchant.findFirst({
What was your reasoning towards `findFirst` over `findUnique` impl?

2024-06-09 20:12 UTC, thomas779 commented on src/v1/middleware.ts
> +  const merchant = await prisma.merchant.findFirst({
`findUnique` seems to have better performance since it is querying against unique fields

2024-06-09 20:12 UTC, thomas779 commented on src/v1/middleware.ts
> +    }
Will the `throw new Error()` response get returned to the client? How do we plan to handle duplicate data on the client-side?

2024-06-09 20:12 UTC, thomas779 commented on src/v1/middleware.ts
> +      }
How come we are checking if a wallet is used too frequently if a wallet can only be used once?

2024-06-09 20:12 UTC, thomas779 commented on src/v1/schemas/merchant.ts
Let's avoid over-commenting. Some of the schema syntax is self-explanatory. You could argue regex patterns are unclear, so happy to keep that in.

2024-06-09 20:12 UTC, thomas779 commented on src/v1/types/transaction.ts
This file shouldn't be imported?

2024-06-13 22:06 UTC, Dyl4n-C0de commented on src/v1/middleware.ts
> +  const merchant = await prisma.merchant.findFirst({
findUnique in Prisma is designed to retrieve a single record based on a unique identifier- findFirst allows for more complex queries, and exits early on match. In this case we need to check if any merchant exists with any of the given unique identifiers (email, phone number, or wallet address).

2024-06-13 22:24 UTC, Dyl4n-C0de commented on src/v1/middleware.ts
> +    }
The client application should handle these responses by displaying the appropriate error messages- we can return a 409 to properly communicate this on the client side.

2024-06-13 22:27 UTC, Dyl4n-C0de commented on src/v1/middleware.ts
> +      }
Didnt get a clear answer on this, there is an edge case where 2 merchants could use the same wallet.

2024-06-13 22:30 UTC, Dyl4n-C0de commented on src/v1/middleware.ts
> +      }
I can change if we want to limit

```
if (walletCount > 0) 
```

2024-06-13 22:31 UTC, Dyl4n-C0de commented on src/v1/schemas/merchant.ts
agreed, just specific to a few changes so wanted to make sure I was clear.

2024-06-13 22:34 UTC, Dyl4n-C0de commented on src/v1/types/transaction.ts
I was using it as a reference for the merchant schema. specifically ISO3166Alpha2Country and ISO3611_2USAState, but we now have the regex in the merchant schema, so I will remove it

2024-06-29 09:59 UTC, thomas779 approved these changes

2024-06-29 10:00 UTC, merged